# Generated by Django 5.0 on 2024-04-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0009_projectsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsummary',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updatecashin',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updatecashout',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectsummary',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectsummary',
            name='cash_in',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectsummary',
            name='cash_out',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
