# Generated by Django 5.0 on 2024-04-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0010_projectsummary_service_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsummary',
            name='service_date',
        ),
        migrations.RemoveField(
            model_name='updatecashin',
            name='service_date',
        ),
        migrations.RemoveField(
            model_name='updatecashout',
            name='service_date',
        ),
    ]
