# Generated by Django 5.0 on 2024-04-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0011_remove_projectsummary_service_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsummary',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updatecashin',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updatecashout',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
